### PR TITLE
readmeの更新

### PR DESCRIPTION
**Pull request by nomurakkooo**
## 概要
- README.mdの更新
## 技術的変更点
- 変更点特筆無し
## ToDo
- [x] README.mdの更新

### CODE REVIEW

**Comment by kkenya** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@kkenya/BookSeeker-add-readme

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by kkenya** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@kkenya/BookSeeker-add-readme

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by kkenya** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@kkenya/BookSeeker-add-readme

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by kkenya** [comment]
写真あるとすごいよく見える
丁寧なREADMEありがとう！

**Comment by nomurakkooo** [comment]
マージします！

**Pull request merged**
